# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    # both_arms_joint_trajectory_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    left_robotiq_gripper_controller:
      type: position_controllers/GripperActionController


    right_robotiq_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - leftjoint_1
      - leftjoint_2
      - leftjoint_3
      - leftjoint_4
      - leftjoint_5
      - leftjoint_6
      - leftjoint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
    state: active 

right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - rightjoint_1
      - rightjoint_2
      - rightjoint_3
      - rightjoint_4
      - rightjoint_5
      - rightjoint_6
      - rightjoint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
    state: active

# both_arms_joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - leftjoint_1
#       - leftjoint_2
#       - leftjoint_3
#       - leftjoint_4
#       - leftjoint_5
#       - leftjoint_6
#       - leftjoint_7
#       - rightjoint_1
#       - rightjoint_2
#       - rightjoint_3
#       - rightjoint_4
#       - rightjoint_5
#       - rightjoint_6
#       - rightjoint_7
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     state_publish_rate: 100.0
#     action_monitor_rate: 20.0
#     allow_partial_joints_goal: false
#     constraints:
#       stopped_velocity_tolerance: 0.0
#       goal_time: 0.0
#     state: inactive

left_robotiq_gripper_controller:
  ros__parameters:
    joint: leftrobotiq_85_left_knuckle_joint
right_robotiq_gripper_controller:
  ros__parameters:
    joint: rightrobotiq_85_left_knuckle_joint