<?xml version="1.0"?>
<robot name="rosie" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- include files -->
    <xacro:arg name="robot_namespace" default="/" />
     

    
    <xacro:include filename="$(find rosie_description)/urdf/tracer_wheel_1.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/tracer_wheel_2.xacro" />

    <xacro:include filename="$(find rosie_description)/urdf/fr_castor.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/fl_castor.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rr_castor.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rl_castor.xacro" />

    <xacro:include filename="$(find rosie_description)/urdf/fr_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/fl_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rr_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rl_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/zed_descr.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/zed_macro.xacro" />
    <!--xacro:include filename="$(find rosie_description)/urdf/rosie_arms.xacro" /-->
    <!--xacro:include filename="$(find rosie_description)/urdf/dual_arms.xacro" /-->    

    
  
 
 <!-- Variables -->
        <xacro:property name="M_PI" value="3.14159"/>

        <!-- Vehicle Geometries -->
        <xacro:property name="base_x_size" value="0.6200000" />
        <xacro:property name="base_y_size" value="0.585000" />
        <xacro:property name="base_z_size" value="0.235000" />

        <xacro:property name="wheelbase" value="0.34"/><!--0.33515-->
        <xacro:property name="track" value="0.37910" /><!--0.37810-->

        <xacro:property name="castor_length" value="0.002"/>
        <xacro:property name="castor_radius" value="0.03724" />

        <xacro:property name="wheel_vertical_offset" value="-0.082" />
        <xacro:property name="castor_offset" value="0.03" />

        <xacro:property name="wheel_length" value="0.8e-01" />
        <xacro:property name="wheel_radius" value="1.600e-01" />


<!--odom link-->

    <link name="odom" />

<!--odom & base_footprint joint-->

    <joint name="odom_base_footprint_joint" type="fixed">
        <parent link="odom" />
        <child link="base_footprint"/>
    </joint>

<!-- Base Link -->
    <link name="base_link">
      <visual>
       <geometry>
              <mesh filename="package://rosie_description/meshes/rosie/rosie_no_arms.dae" />
       </geometry>
        <origin xyz="0 0 -0.107" rpy="-1.57 0 -1.57" />
      </visual>
      <collision>
        <geometry>
               <mesh filename="package://rosie_description/meshes/rosie/rosie_no_arms.dae" />
        </geometry>
         <origin xyz="0 0 -0.107" rpy="-1.57 0 -1.57" />
      </collision>
    </link>
<!-- Robot Footprint -->
    <link name="base_footprint">
    <origin xyz="0 0 0.0" rpy="-1.57 0 -1.57" />
    </link>

    <joint name="foot_print_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.143" rpy="0 0 0"/>
    </joint>



<!--tracer castor wheel-->
      <xacro:tracer_wheel_1 wheel_prefix="right">
          <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
      </xacro:tracer_wheel_1>
      <xacro:tracer_wheel_2 wheel_prefix="left">
          <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
      </xacro:tracer_wheel_2>


      <xacro:fl_castor wheel_prefix="fl_castor">
          <origin xyz="${track/2} ${wheelbase/2} ${castor_offset}" rpy="-1.57 0 0" />
      </xacro:fl_castor>
      
      <xacro:fr_castor wheel_prefix="fr_castor">
          <origin xyz="${track/2} ${-wheelbase/2} ${castor_offset}" rpy="-1.57 0 0" />
      </xacro:fr_castor>
      <xacro:rr_castor wheel_prefix="rr_castor">
          <origin xyz="${-track/2} ${-wheelbase/2} ${castor_offset}" rpy="-1.57 0 0" />
      </xacro:rr_castor>
      <xacro:rl_castor wheel_prefix="rl_castor">
          <origin xyz="${-track/2} ${wheelbase/2} ${castor_offset}" rpy="-1.57 0 0" />
      </xacro:rl_castor>



      <xacro:fl_wheel wheel_prefix="fl">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:fl_wheel>
      <xacro:fr_wheel wheel_prefix="fr">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:fr_wheel>
      <xacro:rr_wheel wheel_prefix="rr">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:rr_wheel>
      <xacro:rl_wheel wheel_prefix="rl">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:rl_wheel>

 <!-- zed camera 1-->
     <link name="front_camera">
       <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />

     </link>

    <xacro:zed_camera name="front" model="zedx" parent="front_camera">
     <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:zed_camera>
    <joint name="front_camera_base_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_camera"/>
        <origin xyz="0.345 0.0 ${0.345-0.107}" rpy="0 0 0"/>
    </joint>
<!-- zed camera 2-->   
    <link name="rear_camera">
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />

    </link>

    <xacro:zed_camera name="rear" model="zedx" parent="rear_camera">
    <origin xyz="0 0 0" rpy="0 0 -3.14159" />
    </xacro:zed_camera>
    <joint name="rear_camera_base_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_camera"/>
        <origin xyz="-0.345 0.0 ${0.345-0.107}" rpy="0 0 0"/>
    </joint>
    

 <!-- Imu link-->
    <link name="imu_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="0.01 0.01 0.01"/>
        </geometry>
    </visual>
    
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <box size="0.01 0.01 0.01"/>
        </geometry>
    </collision>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0.15 -0.064 ${0.611-0.107}" rpy="0 3.14159  1.57"/>
    </joint>

    <link name="arm_world" />
    <joint name="arm_world_base_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_world"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

</robot>
