<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="tracer">
  <!-- include files -->
  
     

    <xacro:include filename="$(find rosie_description)/urdf/tracer_wheel_1.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/tracer_wheel_2.xacro" />

    <xacro:include filename="$(find rosie_description)/urdf/fr_castor.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/fl_castor.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rr_castor.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rl_castor.xacro" />

    <xacro:include filename="$(find rosie_description)/urdf/fr_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/fl_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rr_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/rl_wheel.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/zed_descr.xacro" />
    <xacro:include filename="$(find rosie_description)/urdf/zed_macro.xacro" />
 
 <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.34"/><!--0.33515-->
    <xacro:property name="track" value="0.37910" /><!--0.37810-->

    <xacro:property name="castor_length" value="0.002"/>
    <xacro:property name="castor_radius" value="0.03724" />

  <!-- <xacro:property name="wheel_vertical_offset" value="-0.0777463" />-->
  <!--<xacro:property name="wheel_vertical_offset" value="-0.0749083" />-->
  <xacro:property name="wheel_vertical_offset" value="-0.082" />
  <xacro:property name="castor_offset" value="0.03" />

<!--    <xacro:property name="track" value="0.3426" />
    <xacro:property name="wheelbase" value="0.3181"/>
    <xacro:property name="wheel_vertical_offset" value="-0.160000047342231" />-->

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />


   
    
    <link name="tracer_base_link">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57" />
    </link>
    <joint name="tracer_base_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="tracer_base_link"/>
        <origin xyz="0 0 0.103" rpy="0 0 0"/>
    </joint>
      <xacro:tracer_wheel_1 wheel_prefix="right">
          <origin xyz="0 ${-wheelbase/2} ${wheel_vertical_offset}" rpy="0 0 0" />
      </xacro:tracer_wheel_1>
      <xacro:tracer_wheel_2 wheel_prefix="left">
          <origin xyz="0 ${wheelbase/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
      </xacro:tracer_wheel_2>

  <!--tracer castor wheel-->

      <xacro:fl_castor wheel_prefix="fl_castor">
          <origin xyz="${track/2} ${wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
      </xacro:fl_castor>
      <xacro:fr_castor wheel_prefix="fr_castor">
          <origin xyz="${track/2} ${-wheelbase/2} ${castor_offset-0.0528886}" rpy="-1.57 0 0" />
      </xacro:fr_castor>
      <xacro:rr_castor wheel_prefix="rr_castor">
          <origin xyz="${-track/2} ${-wheelbase/2} ${castor_offset-0.0528886+}" rpy="-1.57 0 0" />
      </xacro:rr_castor>
      <xacro:rl_castor wheel_prefix="rl_castor">
          <origin xyz="${-track/2} ${wheelbase/2} ${castor_offset-0.0528886+0.103}" rpy="-1.57 0 0" />
      </xacro:rl_castor>



      <xacro:fl_wheel wheel_prefix="fl">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:fl_wheel>
      <xacro:fr_wheel wheel_prefix="fr">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:fr_wheel>
      <xacro:rr_wheel wheel_prefix="rr">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:rr_wheel>
      <xacro:rl_wheel wheel_prefix="rl">
          <origin xyz="-0.0218084 ${-wheel_vertical_offset-0.0150} 0" rpy="0 0 0" />
      </xacro:rl_wheel>

  
















</robot>
